Se llenan las tablas de solicitud y requisitos que hacían falta
udistrital/tesoreria_mid pull request #16
Opened 2021-08-18 18:09 UTC by diagutierrezro

https://github.com/udistrital/tesoreria_cliente/issues/116

2021-08-20 00:23 UTC, AlexFBP requested changes
Para la mayoría de los comentarios, usar las siguientes referencias:
- [Codigos de Estado HTTP - MDN](https://developer.mozilla.org/es/docs/Web/HTTP/Status)
- [Beego logs module](https://beego.me/docs/module/logs.md)

Adicional a lo comentado, en uno de los commit se agregó un binario (tesorería_mid.exe~), por lo que es necesario un `git rebase -i develop` para quitar el binario de la rama y commit (de la historia). Contactame y te ayudo a quitarlo

2021-08-20 00:23 UTC, AlexFBP commented on controllers/solicitud_avance.go
> +		fmt.Println(err1)
Preferible usar `logs.Error()` de "github.com/astaxie/beego/logs":
https://github.com/udistrital/tesoreria_mid/blob/6fb336ec5c9c55c87528bf8721b9e970dbb20288/helpers/errorctrl.go#L11
También se puede usar [otro tipo de log](https://beego.me/docs/module/logs.md) (en vez de `.Error()`) según sea el caso

2021-08-20 00:23 UTC, AlexFBP commented on conf/app.conf
> +runmode = ${RUN_MODE}
Dejar estas variables como estaban, o confirmar con @fernandotower o @mafeave si se pueden cambiar

2021-08-20 00:23 UTC, AlexFBP commented on controllers/solicitud_avance.go
>  			panic(helpers.Error("Post", err3, "400"))
Si el error que retorna `helpers.CrearSolicitudAvance()` es un error estructurado, en el `else` retornar el código de error retornado, en vez del `"400"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/apicon.go
> +		return nil, Error(funcion, "No se reconoce v", "502")
Usar 400 en vez del 502: sería un error de usuario al usar este helper

2021-08-20 00:23 UTC, AlexFBP commented on helpers/apicon.go
> +			return nil, Error(funcion, err, "502")
OK: Reservar el 502 cuando fallen las peticiones a APIs

2021-08-20 00:23 UTC, AlexFBP commented on helpers/apicon.go
> +				return nil, Error(funcion, err, "502")
En este caso, el 502 _podría_ cambiarse por un 500
(Mirar si vale la pena)

2021-08-20 00:23 UTC, AlexFBP commented on helpers/apicon.go
> +			return nil, Error(funcion, err, "502")
Ok (502 para fallo en peticiones a APIs externas)

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return nil, Error(funcion, err2, "502")
Si `EnviarSolicitante()` retorna un error estructurado, usar el codigo del `err2` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return nil, Error(funcion, errObj, "502")
Si `EnviarObservacion()` retorna un error estructurado, usar el codigo del `errObj` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return nil, Error(funcion, errJust, "502")
Si `EnviarObservacion()` retorna un error estructurado, usar el codigo del `errJust` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			}
Si no es importante el `err4` (el `else`), aunque sea imprimirlo en consola en el `else` como un `logs.Warn()`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return Error(funcion, err, "502")
Si `EnviarSolicitudCrud()` retorna un error estructurado, usar el codigo del `err` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return Error(funcion, err, "502")
Si `ObtenerSolicitantePorSolicitudId()` retorna un error estructurado, usar el codigo del `err` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  				return Error(funcion, err, "502")
Si `EnviarSolicitante()` retorna un error estructurado, usar el codigo del `err` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  				return Error(funcion, errObj, "502")
Si `EnviarObservacion()` retorna un error estructurado, usar el codigo del `errObj` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  			return Error(funcion, err, "502")
Si `ObtenerObjetivoPorSolicitudId()` retorna un error estructurado, usar el codigo del `err` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  				return Error(funcion, errJust, "502")
Si `EnviarObservacion()` retorna un error estructurado, usar el codigo del `errJust` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, Error(funcion, err1, "502")
Si `Add()` y `Update()` retornan un error estructurado, usar el codigo del `err1` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
>  	defer ErrorControlFunction(funcion, "502")
**General**: Usar 500 en los defer

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		return nil, Error(funcion, err1, "502")
Si `Add()` y `Update()` retornan un error estructurado, usar el codigo del `err1` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		return nil, Error(funcion, err1, "502")
Si `Add()` y `Update()` retornan un error estructurado, usar el codigo del `err1` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		return nil, Error(funcion, err1, "502")
Si `Add()` y `Update()` retornan un error estructurado, usar el codigo del `err1` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		panic(errDecod)
Evitar el `panic()` en los helpers
```diff
-panic(errDecod)
+return nil,Error(...)
```

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			panic(errJson)
Evitar el `panic()` en los helpers
```diff
-panic(errJson)
+return nil,Error(...)
```

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			fmt.Println("FALLO por id")
Evitar fmt y cambiar por beego logs:
```diff
-fmt.Print(...)
+logs.Error(...)
```
Si no es `.Error(...)` usar el `logs.???` adecuado

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		fmt.Println(err1)
Cambiar fmt por logs.? (o comentar si no es importante)

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		panic(errDecod)
`return nil, Error()`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		panic(errJson)
`return nil, Error()`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, Error(funcion, err, "502")
Si `GetAll()` retorna un error estructurado, usar el codigo del `err` en vez del `"502"`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			fmt.Println("res ", res)
1. fmt -> logs.? (o comentar/eliminar)
2. (ver línea 387)

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			fmt.Println("FALLO por id")
fmt -> logs.? (o comentar/eliminar)

2021-08-20 00:23 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		fmt.Println(err1)
1. fmt -> logs.? (o comentar/eliminar)
2. (De la L381) No se está evaluando `err1 == nil`. Esto está bien? Confirmar que si `Add` retorna error se puede descartar. En otras palabras, confirmar que **no** se necesita `return nil, Error` cuando `err1 != nil`

2021-08-20 00:23 UTC, AlexFBP commented on helpers/apicon.go
>  	defer ErrorControlFunction(funcion, "502")
**General**: Usar 500 en los defer al comienzo de los helper

2021-08-20 17:31 UTC, diagutierrezro commented on helpers/apicon.go
> +			return nil, Error(funcion, err, "502")
Si lo que se retorna es de tipo error se arma el map[string] con la función Error y en caso de que ya se traiga el map[string] de la función simplemente se retorna ese mismo map ya que se asume que debe tener el status code especificado dentro del map

2021-08-20 18:12 UTC, diagutierrezro commented on helpers/apicon.go
> +				return nil, Error(funcion, err, "502")
![image](https://user-images.githubusercontent.com/38676533/130271900-7c7a5f84-48d1-4ff7-85ec-35e09ff69b29.png)
Se realiza el cambio a status code 500 desde donde se generaría el error inicialmente

2021-08-20 18:12 UTC, diagutierrezro commented on helpers/solicitud_avance.go
>  			return nil, Error(funcion, err2, "502")
![image](https://user-images.githubusercontent.com/38676533/130272968-b3365344-f883-40d1-a4e0-63ac806dd4d2.png)
Se retorna unicamente "err" ya que es un map[string] que ya trae el status code dentro de la estructura.
![image](https://user-images.githubusercontent.com/38676533/130272731-1a427795-4fc1-4004-acbf-7db3144ac156.png)
Este status se maneja desde el controller en caso de que haya algun error

2021-08-20 18:12 UTC, diagutierrezro commented on helpers/solicitud_avance.go
>  			return nil, Error(funcion, errObj, "502")
![image](https://user-images.githubusercontent.com/38676533/130273987-e2c407ee-e2f2-4e96-82f7-852fb9b67f6c.png)
Ya que el error viene como map[string] se retorna simplemente ese mismo y se maneja desde el controller

2021-08-20 18:12 UTC, diagutierrezro commented on helpers/solicitud_avance.go
>  			return Error(funcion, err, "502")
![image](https://user-images.githubusercontent.com/38676533/130274430-f55aacfb-2db2-4613-b027-29403f00e0d8.png)
Se retorna unicamente el map[string] y se maneja desde el controller

2021-08-21 06:59 UTC, AlexFBP requested changes

2021-08-21 06:59 UTC, AlexFBP commented on helpers/apicon.go
>  		}
Cuando `element == nil` este `else` no está haciendo nada (porque para evaluar lo mencionado tuvo que haberse cumplido que `err == nil`). Eso es correcto?

2021-08-21 06:59 UTC, AlexFBP commented on helpers/apicon.go
> +	return Error("ResultToStruct", resultado, resultado["Status"].(string))
`resultado` puede llegar a ser un error estructurado? (como argumento de esta funcion?)
Confirmar. Si no, usar un codigo HTTP fijo

2021-08-21 06:59 UTC, AlexFBP commented on helpers/apicon.go
> +			return nil, Error(funcion, error, "400")
En este caso sí se podía haber dejado el 502, dado que para que entre acá fue porque falló el `request.SendJson()`, un error externo a este MID, mas no del usuario

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, err2
Cuando `err2 != nil`, muy seguramente va a pasar que `res2 == nil`, por lo que NO va a entrar a este `if` gracias al `&&`. Adicionalmente, considerando que no se está usando `res2` dentro del `if`, no es necesario evaluar si `res2 != nil`

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, errObj
Quitar `&& resObj != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, errJust
Quitar `&& resJust != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		if res3, err3 := EnviarSolicitudAvanceCrud(&solicitudAvanceCrud); err3 == nil && res3 != nil {
Quitar `&& res3 != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return err
Quitar `&& res != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +				return err
Quitar `&& res != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +				return errObj
Quitar `&& resObj != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +				return errJust
Quitar `&& resJust != nil` de acuerdo a lo mencionado

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		return nil, Error(funcion, "Sintaxis incorrecta de solRequisito", "400")
De pronto hay información útil en el `errDecod` que se estaría perdiendo al usar solo la frase. Se podría intentar colocar directamente el `errDecod` en vez del "Sintaxis incorrecta de solRequisito" (dependiendo de si `Error()` lo aguanta)
```diff
-Error(funcion, "Sintaxis incorrecta de solRequisito", "400")
+Error(funcion, errDecod, "400")
```

Alternativamente, se podría combinar un mensaje y el error colocando algo como
```go
fmt.Sprintf("Error: %v", errDecod)
```
en vez de la frase, es decir:
```diff
-Error(funcion, "Sintaxis incorrecta de solRequisito", "400")
+Error(funcion, fmt.Sprintf("Error: %v", errDecod), "400")

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +		return nil, Error(funcion, "Error en la decodificación del JSON", "400")
De manera similar, aprovechar `errJson`

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +			return nil, Error(funcion, "No existe solicitante asociado", "502")
Si la API respondió bien, con una respuesta vacía (`err == nil` y `len(requisitoTipoAvance) <= 0`), considerar entre los codigos de estado HTTP 200, 204 o 404, según sea pertinente...
(El 502 indicaría que falló una API externa)

2021-08-21 06:59 UTC, AlexFBP commented on helpers/solicitud_avance.go
> +	defer ErrorControlFunction(funcion, "5000")
500

2021-08-23 16:05 UTC, diagutierrezro commented on helpers/apicon.go
>  		}
En caso de que haya algún error si entra al else ya que si cualquiera de las dos condiciones no se cumple retorna un false.

2021-08-23 16:10 UTC, diagutierrezro commented on helpers/apicon.go
> +	return Error("ResultToStruct", resultado, resultado["Status"].(string))
`resultado` siempre llega estructurado en esta parte del codigo ya que si llegó hasta ahi es porque anteriormente hizo alguna petición a otra api las cuales ya vienen refactorizadas y traen una estructura de Data, Message, Status y Success

2021-08-23 16:27 UTC, diagutierrezro commented on helpers/apicon.go
>  		}
![image](https://user-images.githubusercontent.com/38676533/130483160-62a42eee-6f09-40de-bbef-77feaabd120a.png)
Se realiza la siguiente modificación.

2021-08-23 16:31 UTC, diagutierrezro commented on helpers/solicitud_avance.go
> +			return nil, err2
Se realiza la siguiente modificación 
![image](https://user-images.githubusercontent.com/38676533/130483680-32074411-7a78-4f6a-a3d1-2c53dce80af5.png)

2021-08-23 16:34 UTC, diagutierrezro commented on helpers/solicitud_avance.go
> +		if res3, err3 := EnviarSolicitudAvanceCrud(&solicitudAvanceCrud); err3 == nil && res3 != nil {
En este caso no se puede quitar res3 ya que se envía como parametro mas adelante
![image](https://user-images.githubusercontent.com/38676533/130484117-39404e21-7d36-4619-9099-544c630bc904.png)

2021-08-23 16:42 UTC, diagutierrezro commented on helpers/solicitud_avance.go
> +			return nil, Error(funcion, "No existe solicitante asociado", "502")
Se realiza la modificación del statusCode a 204

2021-08-25 03:22 UTC, AlexFBP approved these changes

2021-08-25 03:22 UTC, AlexFBP commented on helpers/apicon.go
>  		if err := MapToStruct(data, element); err == nil && element != nil {
Solo para no tener "tanto" código duplicado, el comportamiento actual equivale a **quitar** lo que está marcado en azul en la siguiente imagen:

![image](https://user-images.githubusercontent.com/6588872/130719078-cc912e59-5b81-4347-b944-103c328a6f98.png)

Se puede aplicar de manera similar donde aplique

2021-08-26 17:43 UTC, merged