Feature/cuenta bancaria banco
udistrital/tesoreria_mid pull request #19
Opened 2021-10-26 17:42 UTC by Jeisson005

Relacionado a: Issues udistrital/contabilidad_cliente#92 udistrital/financiera_documentacion#363
Este PR, depende de: udistrital/giros_crud/pull/13

Se puede probar el funcionamiento con la rama: [udistrital/tesoreria_mid/tree/feature/cuenta_bancaria_banco_temp](https://github.com/udistrital/tesoreria_mid/tree/feature/cuenta_bancaria_banco_temp)

2021-10-27 03:32 UTC, AlexFBP requested changes
- En general, aunque sobre todo en `helpers/cuenta_bancaria_banco.go` documentar las funciones públicas
- En `controllers/cuenta_bancaria_banco.go` ajustar el swagger - [Documentación Oficial](https://beego.me/docs/advantage/docs.md#application-comment)
- El build está fallando. Se entiende que depende de `giros_crud` pero mientras tanto probar localmente

2021-10-27 03:32 UTC, AlexFBP commented on controllers/cuenta_bancaria_banco.go
> +		panic(errorctrl.Error("GetOne", err, err["status"].(string)))
Falta controlar en el `else` el escenario cuando `err == nil` Y `cuentaBancaria == nil`, podría ser algo así:
```suggestion
		if (cuentaBancaria == nil) {
			panic(errorctrl.Error("GetOne", "Cuenta no existe", "404"))
		}
		panic(errorctrl.Error("GetOne", err, err["status"].(string)))
```

2021-10-27 03:32 UTC, AlexFBP commented on controllers/cuenta_bancaria_banco.go
> +	}
Implementar el `else` de cada `if` de tal manera que retorne un Error 400 (con un mensaje adecuado en cada caso), para no permitir que se llame al helper

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +// Obtiene múltiples cuentas bancarias
```suggestion
// ObtenerCuentasBancariasBancos Obtiene múltiples cuentas bancarias
```

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +// Obtiene una cuenta bancaria por Id
```suggestion
// ObtenerCuentaBancariaBancoPorId Obtiene una cuenta bancaria por Id
```

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +func SetCuentaBancariaBancoPorCuentaBancaria(cuentaBancaria *giros_crud.CuentaBancaria, cuentaBancariaBanco *models.CuentaBancariaBanco) {
```suggestion
// SetCuentaBancariaBancoPorCuentaBancaria ...
func SetCuentaBancariaBancoPorCuentaBancaria(cuentaBancaria *giros_crud.CuentaBancaria, cuentaBancariaBanco *models.CuentaBancariaBanco) {
```

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +func ObtenerInfoComplementariaPorId(id int, cuentaBancariaBanco *models.CuentaBancariaBanco) (res *terceros_crud.InfoComplementariaTercero, err map[string]interface{}) {
```suggestion
// ObtenerInfoComplementariaPorId ...
func ObtenerInfoComplementariaPorId(id int, cuentaBancariaBanco *models.CuentaBancariaBanco) (res *terceros_crud.InfoComplementariaTercero, err map[string]interface{}) {
```

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +func SetCuentaBancariaPorInfoComplementaria(infoComplementaria *terceros_crud.InfoComplementariaTercero, cuentaBancariaBanco *models.CuentaBancariaBanco) {
```suggestion
// SetCuentaBancariaPorInfoComplementaria ...
func SetCuentaBancariaPorInfoComplementaria(infoComplementaria *terceros_crud.InfoComplementariaTercero, cuentaBancariaBanco *models.CuentaBancariaBanco) {
```

2021-10-27 03:32 UTC, AlexFBP commented on controllers/cuenta_bancaria_banco.go
> +// @Success 200 {object} models.Cuenta_bancaria_banco
Colocar el objeto retornado por el helper
```suggestion
// @Success 200 {object} []models.CuentaBancariaBanco
```
Despues de esto, es necesario regenerar el swagger. Validar que se actualice adecuadamente

2021-10-27 03:32 UTC, AlexFBP commented on helpers/cuenta_bancaria_banco.go
> +
```suggestion
// ObtenerCuentaBancariaPorId ...
```

Tener cuidado que el comentario anterior, la descripción de la función; no quede con el espacio que está actualmente en medio, eliminar la L54

2021-10-28 04:13 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +		panic(errorctrl.Error("GetOne", err, err["status"].(string)))
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:14 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +// Obtiene múltiples cuentas bancarias
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:14 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +// Obtiene una cuenta bancaria por Id
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:14 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +func SetCuentaBancariaBancoPorCuentaBancaria(cuentaBancaria *giros_crud.CuentaBancaria, cuentaBancariaBanco *models.CuentaBancariaBanco) {
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:14 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +func ObtenerInfoComplementariaPorId(id int, cuentaBancariaBanco *models.CuentaBancariaBanco) (res *terceros_crud.InfoComplementariaTercero, err map[string]interface{}) {
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:14 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +func SetCuentaBancariaPorInfoComplementaria(infoComplementaria *terceros_crud.InfoComplementariaTercero, cuentaBancariaBanco *models.CuentaBancariaBanco) {
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:15 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +// @Success 200 {object} models.Cuenta_bancaria_banco
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:16 UTC, Jeisson005 commented on helpers/cuenta_bancaria_banco.go
> +
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/0411cccd93d5f8cf92ca51b6b302fae4ddb57e5e

2021-10-28 04:24 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +	}
No se realiza este ajuste, dado que implicaría que los parámetros se volverían obligatorios.
@AlexFBP ¿Podríamos dejarlo así?
Así se encuentran casi todas las APIs, hasta las de CRUD, dado que bee go genera un código haciendo lo mismo que aquí, lo que ocurriría en caso de que los parámetros sean incorrectos es que se ignoran y el funcionamiento es el mismo que sin parámetros (tomando los valores por defecto).
La otra opción es buscar otra alternativa para validar si existe el parámetro y luego intentar hacer el paso al tipo de dato correspondiente, sin embargo, quizás no sea tan necesario por lo que comento arriba.

2021-10-28 04:31 UTC, Jeisson005 commented
@AlexFBP Se realiza lo siguiente:

- [x] En general, aunque sobre todo en `helpers/cuenta_bancaria_banco.go` se documentan las funciones públicas

- [x] En `controllers/cuenta_bancaria_banco.go` se ajusta el swagger según [Documentación Oficial](https://beego.me/docs/advantage/docs.md#application-comment) y se actualizan docs

- [x] Se hace la prueba de forma local
  - Se ejecutó `go mod edit -replace github.com/udistrital/giros_crud=../giros_crud`
  - Se corrió la API giros_crud con docker de manera local y se agregó una cuenta bancaria de prueba
  - Se corrió la API tesoreria_mid apuntando a giros_crud local
  - Se hizo una solicitud de las cuentas al endpoint **cuenta_bancaria_banco**
  - La prueba fue exitosa retornando lo siguiente:
```json
{
    "Data": [
        {
            "Id": 1,
            "NumeroCuenta": 6789,
            "NombreSucursal": "Parque de Santander",
            "NombreBanco": "BANCO DE LA REPÚBLICA"
        }
    ],
    "Message": "Request successful",
    "Status": "200",
    "Success": true
}
```

2021-10-28 04:53 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +	}
Se ajusta en commit https://github.com/udistrital/tesoreria_mid/commit/1521225f4dff28290fa6502a732edf71695b1606

2021-10-28 19:08 UTC, AlexFBP requested changes
Un par de ajustes/revisiones menores...

2021-10-28 19:08 UTC, AlexFBP commented on controllers/cuenta_bancaria_banco.go
> +// @Success 200 {object} []models.Cuenta_bancaria_banco
`Cuenta_bancaria_banco` no existe en models, no es el tipo de dato retornado por `ObtenerCuentasBancariasBancos`

https://github.com/udistrital/tesoreria_mid/blob/1521225f4dff28290fa6502a732edf71695b1606/helpers/cuenta_bancaria_banco.go#L33

Con lo siguiente debería ser suficiente

```suggestion
// @Success 200 {object} []models.CuentaBancariaBanco
```

(Es necesario volver a regenerar los swagger.json/yml despues de lo anterior)

2021-10-28 19:08 UTC, AlexFBP commented on controllers/cuenta_bancaria_banco.go
> +	if v, err := c.GetInt("offset", -1); err == nil {
Posiblemente el valor por defecto deba ser 0 para el offset? Revisar

2021-10-29 04:45 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +// @Success 200 {object} []models.Cuenta_bancaria_banco
Se ajusta en el commit https://github.com/udistrital/tesoreria_mid/commit/23e194b49ff6d61f80fc2c2478aa2fd791ad6cb3

2021-10-29 04:52 UTC, Jeisson005 commented on controllers/cuenta_bancaria_banco.go
> +	if v, err := c.GetInt("offset", -1); err == nil {
No es necesario que sea 0, haciendo las pruebas, en todos los casos funciona de la misma manera, tanto con 0 como con -1.
Eso, dado que en el helper **apicon** se hace la validación:
```go
	if offset >= 0 {
		params["offset"] = strconv.Itoa(offset)
	}
```
Esa validación también se encuentra en el api crud de giros.
Por lo que no hay problema

2021-10-30 19:04 UTC, AlexFBP approved these changes

2021-10-30 19:04 UTC, AlexFBP commented
Merge bloqueado hasta que la compilación sea exitosa (a la fecha está fallando)

2021-11-10 06:30 UTC, AlexFBP approved these changes

2021-11-10 06:31 UTC, merged