Get para obtener bancos que tienen codigos registrado en terceros
udistrital/tesoreria_mid pull request #20
Opened 2021-12-16 03:49 UTC by diagutierrezro

udistrital/tesoreria_cliente/issues/143

2021-12-16 14:49 UTC, AlexFBP requested changes
En general bien. Casi todos son ajustes menores y/o _suggested changes_ pero hay un par de consideraciones/recomendaciones adicionales que valdría la pena de una vez incluir

2021-12-16 14:49 UTC, AlexFBP commented on .develop.env
> +export TERCEROS_CRUD_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8121/v1/
(En general) Dejar vacía la última línea de cualquier archivo de texto plano seguido por Git
```suggestion
export TERCEROS_CRUD_URL=http://pruebasapi.intranetoas.udistrital.edu.co:8121/v1/

```

2021-12-16 14:49 UTC, AlexFBP commented on controllers/bancos.go
> +func (c *BancoController) GetAll() {
Se recomienda hacer lo posible para agregar parámetros de paginación (limit y offset), y modificar el helper para que los reciba.

A nivel de la lógica, teniendo en cuenta lo anterior, se podría replicar los parámetros que recibe este controlador, a alguna de las peticiones a otras APIs CRUD

Para sanitizar los valores se recomienda aprovechar las [funciones para parsear parámetros de Beego](https://beego.vip/docs/mvc/controller/params.md)

```golang
var err error
var limit int
var offset int
if limit, err = c.GetInt("limit", 10); err != nil {
  panic(...)
}
if offset, err = c.GetInt("offset", 0); err != nil {
  panic(...)
}
```
Nótese que, si bien no está en la documentación oficial, estas funciones aceptan como segundo parámetro el valor por defecto

2021-12-16 14:49 UTC, AlexFBP commented on helpers/bancos.go
> +	defer errorctrl.ErrorControlFunction(funcion, "500")
```suggestion
	defer errorctrl.ErrorControlFunction(funcion+" - Unhandled Error!", "500")
```

2021-12-16 14:49 UTC, AlexFBP commented on helpers/bancos.go
> +	}
Considerar/Revisar: Es posible reescribir un poco para negar la lógica y que el flujo se vea como un _pipeline_?
Es decir, que en la mayoría de casos lo que se procese (asuma) primero sea el error, más que el éxito? Lo cual permitiría que el código no tenga tanta "profundidad", no quede tan ancho
:arrow_right: [Planteamiento/Ejemplo](https://github.com/udistrital/arka_mid/pull/197#pullrequestreview-829748755)

2021-12-16 16:43 UTC, diagutierrezro commented on helpers/bancos.go
> +	}
Se modifica 
![image](https://user-images.githubusercontent.com/38676533/146412819-60ab0a60-d9cd-47b9-a69f-ed538b24179a.png)

2021-12-16 17:30 UTC, diagutierrezro commented on controllers/bancos.go
> +func (c *BancoController) GetAll() {
Se reciben parametros limit y offset y se manejan desde el helper
![image](https://user-images.githubusercontent.com/38676533/146420132-13b321ee-674a-4123-8750-3cf81cd5dc72.png)

2021-12-18 04:49 UTC, AlexFBP approved these changes

2021-12-18 04:49 UTC, merged